import dynamic from "next/dynamic";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";
// import { alma } from "remote1/alma";

// const alma = import("remote1/alma").then((mod) => mod.alma);

// note: this doesn't work yet :(
// const RemoteButton = dynamic(() => import("remote2/Button"), { ssr: true });
const RemoteButton = dynamic(() => import("remote4/Button"), { ssr: true });

export default function Home() {
  const [isRemoteVisible, setIsRemoteVisible] = useState(true);
  const onButtonClick = async () => {
    // note: these works nicely
    // const { alma } = await import("remote1/alma");
    // const { korte } = await import("remote1/korte");
    // const Button = (await import("remote2/Button")).default;
    // const Message = (await import("remote2/Message")).default;
    // const { banan } = await import("remote3/banan");
    // const { narancs } = await import("remote3/narancs");

    setIsRemoteVisible((value) => !value);

    // console.log(await Remote2Button);
    // console.log(alma());
    // console.log(korte());
    // console.log(banan());
    // console.log(narancs());
    // console.log(Button);
    // console.log(Message);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <button onClick={onButtonClick}>Button</button>

        {isRemoteVisible && <RemoteButton />}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
